apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: petclinic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: ghcr.io/zzhswy/spring-petclinic-customers-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://demo-db:5432/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: petclinic-demo
spec:
  selector:
    app: customers-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
