apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-client
  namespace: petclinic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synthetic-client
  template:
    metadata:
      labels:
        app: synthetic-client
    spec:
      containers:
        - name: synthetic-client
          image: ghcr.io/zzhswy/spring-petclinic-synthetic-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: synthetic-client
  namespace: petclinic-demo
spec:
  type: NodePort
  selector:
    app: synthetic-client
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30098
