apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: ghcr.io/zzhswy/spring-petclinic-vets-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://demo-db:5432/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: petclinic-demo
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
